(function(){
  const shuffle=a=>[...a].sort(()=>Math.random()-.5);
  const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
  const ageLabel=p=>p.ageBand==='teen'?'14-17 años':p.ageBand==='middle'?'12-13 años':'10-12 años';

  function expand(base,target,prefix){
    const contexts=['clase','deporte','amistad','tecnología','viaje','ocio','proyecto','redes','familia','actividad de grupo'];
    const out=base.map((x,i)=>({...x,id:x.id||`${prefix}-${i}`}));let i=0;
    while(out.length<target){const src=base[i%base.length],ctx=contexts[Math.floor(i/base.length)%contexts.length];out.push({...src,id:`${prefix}-v-${i}`,text:`${clean(src.text||src.q||src.question)} Aplica o explica tu respuesta pensando en un contexto de ${ctx}.`});i++;}
    return out.slice(0,target);
  }
  function geometryPool(){
    const out=[];let id=0;const shapes=[['triángulo',3],['cuadrado',4],['rectángulo',4],['pentágono',5],['hexágono',6],['heptágono',7],['octógono',8],['decágono',10]];
    shapes.forEach(([s,n])=>{out.push({id:`wg${id++}`,text:`Dibuja un ${s}, marca sus vértices y escribe cuántos lados tiene.`});out.push({id:`wg${id++}`,text:`Escribe un objeto cotidiano que recuerde a un ${s} y explica qué propiedad geométrica comparten.`});});
    [20,32,47,58,71,88,90,102,117,129,143,156,171,180].forEach(d=>out.push({id:`wg${id++}`,text:`Clasifica un ángulo de ${d}° como agudo, recto, obtuso o llano.`}));
    [18,27,33,41,52,64,73,79].forEach(d=>out.push({id:`wg${id++}`,text:`Calcula el ángulo complementario de ${d}°.`}));[101,113,124,136,148,159,167].forEach(d=>out.push({id:`wg${id++}`,text:`Calcula cuánto falta a ${d}° para formar un ángulo llano.`}));
    ['Explica una diferencia entre un cuadrado y un rectángulo.','Dibuja dos rectas paralelas y dos rectas perpendiculares.','Dibuja un rombo y marca un par de lados paralelos.','Dibuja una figura con exactamente cinco lados.','Explica con tus palabras qué es un vértice.','Explica qué significa que dos lados sean paralelos.','Dibuja un eje de simetría en una figura que lo tenga.','Indica cuántos grados suman los ángulos de un triángulo.','Construye una figura usando al menos un triángulo, un rectángulo y un círculo.'].forEach(t=>out.push({id:`wg${id++}`,text:t}));return expand(out,120,'wg');
  }
  function languageGrammarPool(){const base=[
    'Escribe una oración con un sustantivo, un verbo y un adjetivo y señala cada categoría.','Escribe una palabra simple y una compuesta y explica la diferencia.','Transforma «las jugadoras rápidas» a masculino singular.','Transforma «el alumno atento» a femenino plural.','Escribe una frase con un pronombre personal y otra con un determinante demostrativo.','Escribe una frase con un adverbio de tiempo y otra con una preposición.','Señala sujeto y predicado en: «Los vecinos prepararon una fiesta».','Inventa una oración cuyo sujeto tenga al menos tres palabras.','Escribe una oración en pasado y transfórmala al futuro.','Une dos frases con «sin embargo» sin perder el sentido.','Une dos frases con «porque» expresando una causa.','Escribe una oración con sujeto omitido y explica cuál sería.','Escribe una oración interrogativa y otra exclamativa.','Escribe una oración coordinada con «y» y otra con «pero».','Subraya el núcleo del sujeto en: «Las nuevas bicicletas llegaron temprano».','Identifica el verbo y su tiempo en: «Mañana visitaremos el museo».','Escribe una frase en la que «rápido» funcione como adjetivo.','Escribe una frase en la que aparezca un adverbio de lugar.','Transforma una oración singular en plural manteniendo la concordancia.','Corrige la concordancia de: «Esas perro pequeño corre rápido».'
  ].map((text,i)=>({id:`wlg-${i}`,text}));return expand(base,120,'wlg');}
  function languageSpellingPool(){const words=['bicicleta','ventana','biblioteca','viaje','volver','buscar','bebida','vecino','verano','viento','campo','tiempo','también','empezar','imposible','embudo','comprar','enviar','huevo','hielo','hora','hacer','hablar','hospital','humano','historia','viaje','proteger','reloj','dirigir','llave','yema','caballo','playa','camión','lápiz','árbol','teléfono'];const base=words.map((w,i)=>({id:`wls-${i}`,text:`Escribe correctamente la palabra «${w}», sepárala en sílabas y crea una oración que muestre su significado.`}));base.push({id:'wls-c1',text:'Corrige y explica los cambios: «yo e ido a ver si ay alguien».`'.replace('`','')},{id:'wls-c2',text:'Corrige mayúsculas, tildes y puntuación: «mañana ire a madrid con ana».`'.replace('`','')},{id:'wls-c3',text:'Escribe cinco palabras con b y cinco con v sin repetir raíces.'},{id:'wls-c4',text:'Escribe cuatro palabras con h y explica si conoces una palabra relacionada.'},{id:'wls-c5',text:'Escribe cuatro ejemplos en los que aparezca m antes de p o b.'});return expand(base,120,'wls');}
  function languageWritingPool(){const base=[
    'Redacta un mensaje educado para pedir un favor.','Redacta una disculpa breve por llegar tarde.','Resume en tres frases algo que hayas hecho hoy.','Describe un objeto sin decir su nombre para que alguien lo adivine.','Escribe una instrucción clara de cinco pasos.','Reescribe un mensaje impulsivo para que sea firme pero respetuoso.','Cuenta una anécdota breve con inicio, problema y solución.','Escribe un párrafo sobre una afición e incluye una razón por la que te gusta.','Describe un lugar usando al menos cuatro adjetivos diferentes.','Escribe una opinión sobre usar móviles en clase e incluye una razón y un ejemplo.','Convierte una acusación en una observación concreta y respetuosa.','Escribe una petición clara que indique qué necesitas y para cuándo.','Redacta una respuesta educada a un desacuerdo.','Escribe una mini noticia con titular, qué ocurrió, dónde y cuándo.','Escribe una recomendación de un libro, juego, película o actividad para alguien de tu edad.','Resume un problema en dos frases y propone dos soluciones.','Escribe una introducción para una historia de misterio.','Redacta un texto breve comparando dos formas de estudiar.','Escribe un mensaje para organizar un trabajo en grupo.','Reformula una generalización como «nunca me sale bien» de forma más precisa.'
  ].map((text,i)=>({id:`wlw-${i}`,text}));return expand(base,120,'wlw');}
  function divisionPool(){const out=[];let id=0;for(let d of [4,5,6,7,8,9,12,14,15,16,18,21,24,25,27,32,36,42,48,54,63,72,84,96]){for(let k=0;k<5;k++){const q=24+((id*7)%121),r=(id*3)%Math.min(d,11),n=d*q+r;out.push({id:`wd${id++}`,text:`${n.toLocaleString('es-ES')} ÷ ${d} =`,sub:'Cociente: __________   Resto: __________   Comprobación: ____________________'});}}return out.slice(0,120);}
  function mathMiddlePool(){const base=[];for(let i=0;i<120;i++){if(i%5===0){const b=120+i*3,p=[10,15,20,25,30][i%5];base.push({id:`wmm-${i}`,text:`Calcula el ${p}% de ${b} y explica la operación.`});}else if(i%5===1){const x=3+i%12,m=2+i%5,b=4+i%8;base.push({id:`wmm-${i}`,text:`Resuelve y comprueba: ${m}x + ${b} = ${m*x+b}.`});}else if(i%5===2){const n=6+i%15,d=[2,3,4,5][i%4];base.push({id:`wmm-${i}`,text:`Simplifica ${n*d}/${d} y explica el procedimiento.`});}else if(i%5===3){const u=3+i%6,pr=5+i%9;base.push({id:`wmm-${i}`,text:`Si ${u} unidades cuestan ${u*pr} €, calcula cuánto costarán 7 unidades.`});}else{const a=8+i%10,b=5+i%8;base.push({id:`wmm-${i}`,text:`Calcula área y perímetro de un rectángulo de ${a} cm por ${b} cm.`});}}return base;}
  function mathTeenPool(){const out=[];for(let i=0;i<120;i++){if(i%3===0){const p=[12,15,18,22,25,30][i%6],b=120+i*4;out.push({id:`wtm-${i}`,text:`Calcula el ${p}% de ${b} y explica el procedimiento.`});}else if(i%3===1){const x=4+i%12,m=2+i%5,b=3+i%9;out.push({id:`wtm-${i}`,text:`Resuelve y comprueba: ${m}x + ${b} = ${m*x+b}.`});}else{const u=3+i%6,total=u*(8+i%9);out.push({id:`wtm-${i}`,text:`Si ${u} unidades cuestan ${total} €, calcula precio unitario y coste de 5 unidades.`});}}return out;}
  const readingTexts=[
    ['Un vídeo recortado','Un clip de una entrevista se compartió sin la pregunta anterior. La frase era auténtica, pero al ver la entrevista completa el significado cambiaba bastante.','¿Qué información faltaba y por qué era importante?'],
    ['La ayuda de una herramienta','Una alumna usó una herramienta de IA para organizar ideas, pero comprobó cada dato en fuentes que podía citar.','¿Qué diferencia hay entre usar una herramienta para organizar y usarla como única fuente?'],
    ['El equipo que cambió de estrategia','Un equipo llevaba varios partidos perdiendo balones. En vez de practicar solo tiros, trabajó apoyos y pases y creó más ocasiones.','¿Qué problema identificaron y qué cambiaron?'],
    ['La cuenta patrocinada','Un creador recomendó un producto y avisó de que el vídeo estaba patrocinado.','¿Por qué el patrocinio es información relevante aunque no demuestre que la opinión sea falsa?'],
    ['El grupo de estudio','Cuatro estudiantes repartieron un proyecto de forma desigual porque una parte necesitaba más investigación y otra más diseño.','¿Por qué repartir de forma útil no siempre significa repartir exactamente igual?'],
    ['La cifra sin fuente','Una publicación afirmaba un porcentaje muy llamativo, pero no indicaba estudio, muestra ni fecha.','¿Qué datos pedirías antes de aceptar la cifra?'],
    ['La lista de reproducción','Un grupo redujo una lista demasiado larga dejando que cada persona eligiera tres canciones imprescindibles y completando después con variedad.','¿Qué criterio de negociación usaron?'],
    ['Las notificaciones','Durante una semana, un estudiante dejó el móvil lejos durante bloques de estudio y comparó cuánto tardaba antes y después.','¿Qué dato le permite evaluar si la estrategia le funciona?'],
    ['El experimento repetido','Un resultado sorprendente cambió al repetir la medición. Al revisar el procedimiento apareció un error inicial.','¿Por qué repetir una medición ayuda a evaluar un resultado?'],
    ['La interpretación rápida','Una persona tardó horas en responder un mensaje. La otra pensó que estaba enfadada, pero luego supo que tenía un examen.','¿Qué diferencia hay entre el hecho y la interpretación?']
  ];
  function readingPool(){const base=[];let id=0;for(let round=0;round<12;round++)readingTexts.forEach((r,i)=>base.push({id:`wr-${id++}`,text:`Lee: «${r[1]}» ${r[2]} ${round?`Añade una frase justificando tu respuesta con una pista del texto.`:''}`}));return base.slice(0,120);}
  function teenLanguagePool(){const base=['Redacta un mensaje formal para pedir una tutoría.','Convierte una opinión absoluta en una afirmación más precisa.','Escribe un argumento a favor y otro en contra de limitar el móvil en clase.','Resume una noticia ficticia separando hechos de opiniones.','Reescribe un mensaje impulsivo para que sea firme pero respetuoso.','Explica la diferencia entre hecho, opinión e interpretación.','Redacta una respuesta educada a un desacuerdo.','Escribe una petición clara sin sonar exigente.','Escribe una conclusión que incluya una limitación razonable.','Convierte una acusación en una observación concreta.'].map((text,i)=>({id:`wtl-${i}`,text}));return expand(base,120,'wtl');}
  function middleLanguagePool(){const base=['Analiza sujeto y predicado de: «Los estudiantes organizaron el proyecto con cuidado».','Escribe una oración con un pronombre, un adverbio y una preposición.','Reescribe «Nunca me sale bien» de forma más precisa.','Escribe una frase con «sin embargo» y otra con «por tanto».','Corrige la puntuación: «Cuando llegamos nadie sabia que hacer».','Distingue en dos frases un hecho y una opinión sobre una película.','Transforma una acusación en una observación concreta.','Resume en dos frases un problema y una posible solución.','Escribe una frase en estilo directo y pásala a indirecto.','Redacta una petición educada para solicitar una aclaración.'].map((text,i)=>({id:`wml-${i}`,text}));return expand(base,120,'wml');}
  function socialPool(ctx){const base=(ctx.data.social||[]).map((x,i)=>({id:`ws-${i}`,text:`Situación: ${x.q} Escribe qué harías o pensarías y qué información necesitarías antes de sacar conclusiones.`,sub:`Trabaja ${String(x.cat||'perspectiva').toLowerCase()}, límites y una respuesta respetuosa.`}));return expand(base.length?base:[{id:'ws-0',text:'Analiza una situación social ambigua separando hechos, interpretaciones y posibles respuestas.'}],120,'ws');}
  function englishPool(ctx){const band=ctx.profile.ageBand;const base=[];const primary=['Write 4 sentences about your daily routine.','Write a short invitation to a friend including place and time.','Complete five sentences using present simple.','Write three sentences comparing two hobbies.','Write four sentences about a plan using “going to”.','Write a polite request using “Could you...?”.','Write five school words in English and use two in sentences.','Write three past simple sentences about last weekend.','Write a short description of a room using prepositions.','Write a recommendation for a game or sport using “because”.'];const middle=['Write a short review of a game, series or book with one strength and one limitation.','Write a polite disagreement using “I see your point, but...”.','Write five sentences mixing past simple and past continuous.','Explain the difference between “since” and “for” with examples.','Write a first conditional sentence about studying.','Write a short email asking for clarification about an assignment.','Paraphrase a short online claim in more cautious language.','Write three sentences using present perfect.','Write a short paragraph comparing two ways of studying.','Write advice for someone who is tired using modal verbs.'];const teen=['Write a five-sentence opinion about AI literacy at school.','Write a respectful digital boundary in English.','Summarise how you would verify a viral claim.','Write a balanced review without using “good” or “bad”.','Write a paragraph using one counterargument and a conclusion.','Write a formal email asking for an extension.','Explain fact, opinion and interpretation in English.','Write two examples of cautious language: “might”, “suggests”, “appears”.','Compare two sources and mention one limitation.','Write a short response to an online disagreement that stays respectful.'];const src=band==='teen'?teen:band==='middle'?middle:primary;src.forEach((t,i)=>base.push({id:`wen-${i}`,text:t}));return expand(base,120,'wen');}
  function literacyPool(ctx){const band=ctx.profile.ageBand;const themes=band==='teen'?['IA y estudios','redes sociales','privacidad','relaciones','fitness','música y creadores','presión académica','algoritmos','desinformación','bienestar digital']:band==='middle'?['gaming','IA para estudiar','mensajería','deporte','música','vídeos cortos','privacidad','trabajo en grupo','tendencias','hábitos de estudio']:['mundos de bloques','fútbol','vídeos de ciencia','IA para deberes','música','naturaleza','robótica','juegos','excursiones','chats de clase'];const base=[];themes.forEach((t,i)=>{base.push({id:`wlit-a-${i}`,text:`Escribe un texto de 6-8 frases sobre ${t}. Incluye una idea principal y dos detalles que la apoyen.`});base.push({id:`wlit-b-${i}`,text:`Imagina que lees dos opiniones distintas sobre ${t}. Escribe qué información necesitarías para decidir cuál está mejor fundamentada.`});base.push({id:`wlit-c-${i}`,text:`Redacta un titular neutral sobre ${t} y después otro más sensacionalista. Explica la diferencia.`});});return expand(base,120,'wlit');}
  function gamesPool(ctx){const band=ctx.profile.ageBand;const base=[];const prompts=band==='teen'?['Crea cuatro parejas concepto-definición sobre privacidad digital.','Ordena cinco pasos para verificar una afirmación viral.','Escribe cuatro ecuaciones breves y su solución.','Crea cuatro parejas de conectores ingleses y su función.','Escribe un mini reto para distinguir hecho, opinión e interpretación.','Diseña un “verdadero o falso” de cuatro afirmaciones sobre fuentes.']:band==='middle'?['Crea cuatro parejas fracción-decimal.','Ordena una frase en inglés de seis palabras.','Crea cuatro parejas palabra-categoría gramatical.','Escribe cuatro cálculos de porcentajes y resuélvelos.','Diseña cuatro parejas término-definición sobre lectura crítica.','Ordena los pasos de una estrategia de estudio.']:['Crea cuatro parejas figura-número de lados.','Ordena una frase sencilla en inglés.','Crea cuatro parejas verbo-pasado en inglés.','Escribe cuatro divisiones y resuélvelas.','Crea cuatro parejas palabra-categoría gramatical.','Ordena los pasos divide-multiplica-resta-baja.'];prompts.forEach((t,i)=>base.push({id:`wgame-${i}`,text:t}));return expand(base,120,'wgame');}

  function poolFor(key,ctx){
    if(key==='geometry')return geometryPool();if(key==='division')return divisionPool();if(key==='reading'||key==='middleReading')return readingPool();if(key==='middleMath')return mathMiddlePool();if(key==='teenMath')return mathTeenPool();if(key==='middleLanguage')return middleLanguagePool();if(key==='teenLanguage')return teenLanguagePool();if(key==='social')return socialPool(ctx);if(key==='english')return englishPool(ctx);if(key==='literacy')return literacyPool(ctx);if(key==='games')return gamesPool(ctx);
    if(key==='language:grammar')return languageGrammarPool();if(key==='language:spelling')return languageSpellingPool();if(key==='language:writing')return languageWritingPool();if(key==='language')return [...languageGrammarPool().slice(0,40),...languageSpellingPool().slice(0,40),...languageWritingPool().slice(0,40)];return [];
  }
  const labelFor=(key,ctx)=>({
    'language:grammar':'Lengua · Gramática','language:spelling':'Lengua · Ortografía','language:writing':'Lengua · Escritura',english:'English Lab',literacy:'Lectura + Escritura',games:'Game Lab'
  }[key]||ctx.meta[key]?.name||key);
  function takeUnique(pool,count,used){const available=shuffle(pool.filter(x=>!used.has(x.id)));const take=available.slice(0,count);take.forEach(x=>used.add(x.id));return take;}

  async function makeDoc(selected,version,questionCount,ctx,used){
    const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,AlignmentType,BorderStyle,Footer}=window.docx;
    const green='1F633B',light='EDF5E9',sand='F6F1E5',ink='173326',muted='607064',white='FFFFFF';
    const noBorders={top:{style:BorderStyle.NONE,size:0,color:white},bottom:{style:BorderStyle.NONE,size:0,color:white},left:{style:BorderStyle.NONE,size:0,color:white},right:{style:BorderStyle.NONE,size:0,color:white},insideHorizontal:{style:BorderStyle.NONE,size:0,color:white},insideVertical:{style:BorderStyle.NONE,size:0,color:white}};
    const title=selected.length===1?labelFor(selected[0],ctx):'Ficha combinada';
    const header=new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:noBorders,rows:[new TableRow({children:[new TableCell({width:{size:72,type:WidthType.PERCENTAGE},shading:{fill:light},margins:{top:180,bottom:180,left:220,right:160},children:[new Paragraph({children:[new TextRun({text:title.toUpperCase(),bold:true,size:40,color:green,font:'Aptos Display'})]}),new Paragraph({children:[new TextRun({text:`Versión ${version} · ${ageLabel(ctx.profile)} · practica y revisa`,size:21,color:ink,font:'Aptos'})]})]}),new TableCell({width:{size:28,type:WidthType.PERCENTAGE},shading:{fill:green},margins:{top:150,bottom:150,left:100,right:100},children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'LEVEL UP',bold:true,size:27,color:white,font:'Aptos'})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'LEARNING LAB',bold:true,size:13,color:'D9EAD3',font:'Aptos'})]})]})]})]});
    const name=new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:noBorders,rows:[new TableRow({children:[new TableCell({shading:{fill:sand},margins:{top:130,bottom:130,left:180,right:180},children:[new Paragraph({children:[new TextRun({text:`Nombre: ${ctx.profile.name} ____________________    Fecha: __________________`,size:21,color:ink,font:'Aptos'})]})]})]})]});
    const question=(n,text,sub)=>[new Paragraph({spacing:{before:110,after:90,line:310},children:[new TextRun({text:`${n}. `,bold:true,size:23,color:green,font:'Aptos'}),new TextRun({text:clean(text),size:23,color:ink,font:'Aptos'})]}),...(sub?[new Paragraph({spacing:{after:90},children:[new TextRun({text:clean(sub),size:18,color:muted,font:'Aptos'})]})]:[]),new Paragraph({spacing:{after:125},children:[new TextRun({text:'____________________________________________________________________________',size:17,color:'B3BDB3'})]})];
    const children=[header,new Paragraph({text:' ',spacing:{after:30}}),name];
    let n=1,remaining=questionCount;const per=Math.floor(questionCount/selected.length),extra=questionCount%selected.length;
    selected.forEach((key,idx)=>{const need=per+(idx<extra?1:0);if(!need)return;children.push(new Paragraph({spacing:{before:220,after:70},children:[new TextRun({text:labelFor(key,ctx),bold:true,size:25,color:green,font:'Aptos'})]}));const items=takeUnique(poolFor(key,ctx),need,used);items.forEach(it=>children.push(...question(n++,it.text||it.q||it.question,it.sub)));remaining-=items.length;});
    if(n===1)children.push(new Paragraph({text:'No se encontraron ejercicios para la selección.',spacing:{before:200}}));
    const footer=new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'LEVEL UP · Learning Lab  |  Comprueba tus respuestas antes de terminar',size:16,color:muted,font:'Aptos'})]})]});
    const doc=new Document({styles:{default:{document:{run:{font:'Aptos',size:22,color:ink},paragraph:{spacing:{line:300}}}}},sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:620,right:700,bottom:650,left:700}}},footers:{default:footer},children}]});
    return Packer.toBlob(doc);
  }

  async function generateSelection(selected,count,questionCount,ctx){
    const status=document.querySelector('#docxStatus');if(!window.docx){status.textContent='No se ha cargado el generador DOCX. Comprueba la conexión a internet.';return;}if(count>1&&!window.JSZip){status.textContent='No se ha cargado el generador ZIP. Comprueba la conexión a internet.';return;}
    const used=new Set();status.textContent=`Preparando ${count} versión${count>1?'es':''} con ${questionCount} ejercicios por ficha…`;
    try{if(count===1){const blob=await makeDoc(selected,1,questionCount,ctx,used);downloadBlob(blob,'LearningLab_ficha_v1.docx');status.textContent='Ficha creada con los contenidos seleccionados.';return;}const zip=new JSZip();for(let i=1;i<=count;i++){const blob=await makeDoc(selected,i,questionCount,ctx,used);zip.file(`LearningLab_ficha_version_${i}.docx`,blob);}const out=await zip.generateAsync({type:'blob'});downloadBlob(out,`LearningLab_${count}_fichas.zip`);status.textContent=`Lote creado: ${count} DOCX dentro de un ZIP, evitando repeticiones mientras hay banco disponible.`;}catch(e){console.error(e);status.textContent='No se pudo generar la ficha. Vuelve a intentarlo con conexión a internet.';}
  }
  function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
  window.WorksheetGenerator={generateSelection};
})();
