(function(){
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const SUBJECT_LABELS={
    geometry:'Geometría',language:'Lenguaje',division:'Divisiones',reading:'Lectura',middleLanguage:'Lenguaje 12-13',middleMath:'Matemáticas 12-13',middleReading:'Lectura 12-13',teenLanguage:'Lenguaje 14-17',teenMath:'Matemáticas 14-17',social:'Social Lab',english:'English Lab',literacy:'Lectura + Escritura',attention:'Atención',executive:'Funciones ejecutivas',memory:'Memoria',speedReasoning:'Velocidad y razonamiento',applied:'Cognición aplicada'
  };
  const COLORS={ink:'#24314A',nav:'#252B44',nav2:'#313957',accent:'#5B67D6',accentDark:'#444CAD',accentSoft:'#ECEEFF',coral:'#E47B68',cream:'#FFFDF9',bg:'#F4F3F8',line:'#DFE2EC',muted:'#6F7586',lavender:'#F2F3FF',gold:'#D5A94C',white:'#FFFFFF',danger:'#C95D6A'};

  function addStyles(){
    if($('#v163Styles')) return;
    const style=document.createElement('style');
    style.id='v163Styles';
    style.textContent=`
      :root{--bg:${COLORS.bg};--card:${COLORS.cream};--ink:${COLORS.ink};--muted:${COLORS.muted};--line:${COLORS.line};--nav:${COLORS.nav};--nav2:${COLORS.nav2};--accent:${COLORS.accent};--accent-dark:${COLORS.accentDark};--accent-soft:${COLORS.accentSoft};--grass:#8790E3;--grass2:#AAB0EF;--dirt:${COLORS.coral};--stone:#8E96A9;--sand:#F1E1C6;--danger:${COLORS.danger};}
      body{background:linear-gradient(180deg,#FAF9FC 0,#F1F2F7 100%)}
      .sidebar{background:linear-gradient(180deg,${COLORS.nav},#1D2337);border-right-color:#171C2C}
      .brand-badge{background:${COLORS.accent};box-shadow:inset 0 -8px 0 ${COLORS.coral},4px 4px 0 rgba(0,0,0,.14)}
      .nav-item:hover,.nav-item.active{background:#3A4268;box-shadow:inset 4px 0 0 #AAB0EF}
      .score-chip{background:#303857;border-color:#4E587C}.profile-panel{border-color:#444D70}
      .v16-locale-panel{border-color:rgba(255,255,255,.14);background:rgba(255,255,255,.06)}
      .v16-locale-panel label{color:#D8DBEE}.v16-locale-note{color:#B9BED6}
      #home .hero{background:linear-gradient(135deg,#FFFDF9 0%,#F1F2FF 100%)}
      #home .focus-card{background:linear-gradient(145deg,#343B63,#272C4B)!important}
      .level-track span,.bar span{background:linear-gradient(90deg,${COLORS.accent},#8790E3)!important}
      .primary-btn,.billing-btn{background:${COLORS.accent}!important;border-color:${COLORS.accent}!important}.primary-btn:hover,.billing-btn:hover{background:${COLORS.accentDark}!important}
      .secondary-btn{color:${COLORS.accentDark}!important;border-color:#CBD0F4!important;background:#F0F1FF!important}
      .pill,.language-topic{background:${COLORS.accentSoft}!important;color:${COLORS.accentDark}!important;border-color:#D4D7F4!important}
      .eyebrow{color:${COLORS.accentDark}!important}.v16-toast{background:${COLORS.nav}!important}
      .option-btn.correct,.multi-option.correct{border-color:#7C86DF!important;background:#EEF0FF!important;color:${COLORS.ink}!important}
      .option-btn.wrong,.multi-option.wrong{border-color:#D98C91!important;background:#FCEDEE!important}
      .multi-option.selected:not(.correct):not(.wrong){outline-color:#858EE0!important;background:#F0F1FF!important}
      .search-board{display:grid;gap:8px;margin:14px auto 20px;max-width:920px}.search-board.cols-4{grid-template-columns:repeat(4,1fr)}.search-board.cols-5{grid-template-columns:repeat(5,1fr)}.search-board.cols-6{grid-template-columns:repeat(6,1fr)}
      .search-cell{position:relative;min-height:74px;border:1px solid #D9DDEA;border-radius:12px;background:#FCFBF7;display:flex;align-items:center;justify-content:center;box-shadow:0 3px 0 rgba(36,49,74,.04)}
      .search-cell small{position:absolute;left:8px;top:6px;font-size:.62rem;color:#8A90A0;font-weight:800}.search-cell span{font-size:1.8rem;letter-spacing:.12rem}
      .lh-doc{max-width:780px;margin:16px auto 22px;border:1px solid #D8DDEB;border-radius:16px;background:#FFFDF9;box-shadow:0 12px 30px rgba(46,55,92,.09);padding:22px;color:${COLORS.ink};font-family:Inter,system-ui,sans-serif}
      .doc-kicker{font-size:.7rem;letter-spacing:.13em;font-weight:900;color:${COLORS.accentDark};margin-bottom:9px}.doc-route{display:flex;align-items:center;justify-content:space-between;gap:18px;font-size:1.25rem;padding:12px 0 18px;border-bottom:1px dashed #CCD1E0}
      .doc-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.doc-grid span{padding:10px;background:#F2F3FA;border-radius:9px;color:#73798B;font-size:.78rem}.doc-grid b{font-size:1.05rem;color:${COLORS.ink}}
      .doc-head{display:flex;justify-content:space-between;gap:20px;padding-bottom:12px;border-bottom:1px solid #E0E3EC}.doc-lines{display:grid;gap:8px;padding:14px 0}.doc-lines span,.trip-row{display:flex;justify-content:space-between;gap:16px;padding:8px 0;border-bottom:1px solid #EEEFF4}
      .doc-total{display:flex;justify-content:space-between;align-items:center;padding:13px 15px;background:#EEF0FF;border-radius:10px;font-size:1.05rem}.doc-due,.doc-note{margin-top:12px;padding:9px 12px;background:#FFF1EC;border-radius:8px;color:#7C5146}
      .poster{display:grid;grid-template-columns:90px 1fr;gap:18px;align-items:center;background:linear-gradient(135deg,#FFF8EC,#F0F1FF)}.poster-icon{font-size:3.4rem;text-align:center}.poster h3{margin:2px 0 8px}.poster p{margin:6px 0}
      .itinerary,.timetable{background:#FDFCF8}.trip-row span{flex:1}.trip-row em{font-style:normal;color:#747B8E}
      @media(max-width:800px){.search-board.cols-6,.search-board.cols-5{grid-template-columns:repeat(4,1fr)}.doc-grid{grid-template-columns:repeat(2,1fr)}}
    `;
    document.head.appendChild(style);
    const meta=document.querySelector('meta[name="theme-color"]'); if(meta) meta.setAttribute('content',COLORS.nav);
  }

  function loadScript(src,test){return new Promise((resolve,reject)=>{if(test())return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
  function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1600);}
  function dateText(v){const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return d.toLocaleString('es-ES',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});}

  function lineChart(labels,values,title){
    const canvas=document.createElement('canvas');canvas.width=1100;canvas.height=390;const ctx=canvas.getContext('2d');ctx.fillStyle=COLORS.cream;ctx.fillRect(0,0,canvas.width,canvas.height);
    const L=78,R=35,T=50,B=65,W=canvas.width-L-R,H=canvas.height-T-B;ctx.font='24px Arial';ctx.fillStyle=COLORS.ink;ctx.fillText(title,L,30);ctx.font='16px Arial';ctx.strokeStyle=COLORS.line;ctx.fillStyle=COLORS.muted;ctx.lineWidth=1;
    for(let y=0;y<=100;y+=25){const py=T+H-(y/100)*H;ctx.beginPath();ctx.moveTo(L,py);ctx.lineTo(L+W,py);ctx.stroke();ctx.fillText(`${y}%`,18,py+5);} if(values.length){ctx.strokeStyle=COLORS.accent;ctx.lineWidth=5;ctx.beginPath();values.forEach((v,i)=>{const x=L+(values.length===1?W/2:(i/(values.length-1))*W),y=T+H-(v/100)*H;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();values.forEach((v,i)=>{const x=L+(values.length===1?W/2:(i/(values.length-1))*W),y=T+H-(v/100)*H;ctx.fillStyle=COLORS.coral;ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();});const step=Math.max(1,Math.ceil(labels.length/7));ctx.font='14px Arial';ctx.fillStyle=COLORS.muted;ctx.textAlign='center';labels.forEach((lab,i)=>{if(i%step===0||i===labels.length-1){const x=L+(labels.length===1?W/2:(i/(labels.length-1))*W);ctx.fillText(lab,x,T+H+32);}});}return canvas.toDataURL('image/png');
  }
  function barChart(labels,values,title){
    const canvas=document.createElement('canvas');canvas.width=1100;canvas.height=500;const ctx=canvas.getContext('2d');ctx.fillStyle=COLORS.cream;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font='24px Arial';ctx.fillStyle=COLORS.ink;ctx.fillText(title,62,34);
    const L=250,R=55,T=65,B=32,W=canvas.width-L-R,H=canvas.height-T-B;const n=Math.max(1,labels.length),gap=12,bh=Math.max(22,(H-gap*(n-1))/n);ctx.font='15px Arial';ctx.textBaseline='middle';labels.forEach((lab,i)=>{const y=T+i*(bh+gap);ctx.fillStyle=COLORS.muted;ctx.textAlign='right';ctx.fillText(lab,L-16,y+bh/2);ctx.fillStyle='#E8EAF2';ctx.fillRect(L,y,W,bh);const w=Math.max(0,Math.min(100,values[i]||0))/100*W;ctx.fillStyle=COLORS.accent;ctx.fillRect(L,y,w,bh);ctx.fillStyle=COLORS.ink;ctx.textAlign='left';ctx.fillText(`${Math.round(values[i]||0)}%`,L+w+10,y+bh/2);});return canvas.toDataURL('image/png');
  }

  async function exportExcelV163(){
    const btn=$('#exportSessionCsv');if(btn)btn.disabled=true;
    try{
      await loadScript('https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js',()=>Boolean(window.ExcelJS));
      const api=window.LearningAPI,profileId=$('#profileSelect')?.value;if(!api?.client||!profileId)throw new Error('No hay un perfil activo.');
      const [{data:prof,error:pe},{data:rows,error:re}]=await Promise.all([
        api.client.from('learner_profiles').select('name,age_band,progress').eq('id',profileId).single(),
        api.client.from('exercise_results').select('occurred_at,session_id,session_started_at,subject,level,correct,points,item_id,detail').eq('profile_id',profileId).order('occurred_at',{ascending:true})
      ]);if(pe)throw pe;if(re)throw re;const data=rows||[],sessions=new Map();
      data.forEach((r,i)=>{const sid=r.session_id||`sin_sesion_${i}`;if(!sessions.has(sid))sessions.set(sid,{id:sid,start:r.session_started_at||r.occurred_at,rows:[]});sessions.get(sid).rows.push(r);});
      const sess=[...sessions.values()].map((s,i)=>{const n=s.rows.length,c=s.rows.filter(r=>r.correct).length,p=s.rows.reduce((a,r)=>a+Number(r.points||0),0);return{num:i+1,id:s.id,start:s.start,n,c,e:n-c,acc:n?Math.round(c/n*100):0,p,areas:[...new Set(s.rows.map(r=>SUBJECT_LABELS[r.subject]||r.subject))].join(', '),avg:s.rows.length?s.rows.reduce((a,r)=>a+Number(r.level||1),0)/s.rows.length:1};});
      const areas=new Map();data.forEach(r=>{if(!areas.has(r.subject))areas.set(r.subject,{key:r.subject,n:0,c:0,p:0,level:0});const a=areas.get(r.subject);a.n++;if(r.correct)a.c++;a.p+=Number(r.points||0);a.level+=Number(r.level||1);});
      const areaRows=[...areas.values()].map(a=>({name:SUBJECT_LABELS[a.key]||a.key,n:a.n,c:a.c,acc:a.n?Math.round(a.c/a.n*100):0,p:a.p,avg:a.n?a.level/a.n:1})).sort((a,b)=>b.n-a.n);
      const wb=new ExcelJS.Workbook();wb.creator='Learning Hub';wb.created=new Date();const headerFill=COLORS.nav.replace('#',''),accent=COLORS.accent.replace('#',''),ink=COLORS.ink.replace('#',''),muted=COLORS.muted.replace('#',''),light='ECEEFF',white='FFFFFF',red='FCE8E8';
      const headerStyle=row=>{row.font={bold:true,color:{argb:white}};row.fill={type:'pattern',pattern:'solid',fgColor:{argb:headerFill}};row.alignment={vertical:'middle'};row.height=25;};
      const title=(ws,text,range)=>{ws.mergeCells(range);const c=ws.getCell(range.split(':')[0]);c.value=text;c.font={bold:true,size:20,color:{argb:ink}};c.alignment={vertical:'middle'};ws.getRow(c.row).height=34;};
      const detail=wb.addWorksheet('Detalle',{views:[{state:'frozen',ySplit:1}]});detail.columns=[{header:'Fecha y hora',key:'date',width:22},{header:'Sesión ID',key:'sid',width:22},{header:'Área',key:'subject',width:28},{header:'Nivel',key:'level',width:10},{header:'Ejercicio ID',key:'item',width:31},{header:'Resultado',key:'result',width:14},{header:'Puntos',key:'points',width:11},{header:'Mecánica',key:'detail',width:23}];headerStyle(detail.getRow(1));detail.autoFilter='A1:H1';data.forEach(r=>{const row=detail.addRow({date:dateText(r.occurred_at),sid:r.session_id||'',subject:SUBJECT_LABELS[r.subject]||r.subject,level:r.level,item:r.item_id,result:r.correct?'Correcto':'A revisar',points:r.points||0,detail:r.detail||''});row.alignment={vertical:'top',wrapText:true};row.getCell(6).fill={type:'pattern',pattern:'solid',fgColor:{argb:r.correct?light:red}};});
      const evo=wb.addWorksheet('Evolución por sesiones',{views:[{state:'frozen',ySplit:3}]});title(evo,`Evolución por sesiones · ${prof.name}`,'A1:I1');evo.mergeCells('A2:I2');evo.getCell('A2').value='Una fila por sesión. La precisión permite seguir la evolución sin perder de vista el volumen de práctica.';evo.getCell('A2').font={italic:true,color:{argb:muted}};evo.addRow(['Sesión','Fecha de inicio','Ejercicios','Aciertos','Errores','Precisión','Puntos','Áreas trabajadas','Nivel medio']);headerStyle(evo.getRow(3));evo.columns=[{width:10},{width:22},{width:13},{width:11},{width:11},{width:13},{width:11},{width:44},{width:13}];sess.forEach(s=>{const r=evo.addRow([s.num,dateText(s.start),s.n,s.c,s.e,s.acc/100,s.p,s.areas,s.avg]);r.getCell(6).numFmt='0%';r.getCell(9).numFmt='0.0';r.alignment={vertical:'top',wrapText:true};});evo.autoFilter={from:'A3',to:'I3'};
      const byArea=wb.addWorksheet('Rendimiento por áreas',{views:[{state:'frozen',ySplit:3}]});title(byArea,`Rendimiento por áreas · ${prof.name}`,'A1:F1');byArea.mergeCells('A2:F2');byArea.getCell('A2').value='Resumen por bloque de entrenamiento.';byArea.getCell('A2').font={italic:true,color:{argb:muted}};byArea.addRow(['Área','Ejercicios','Aciertos','Precisión','Puntos','Nivel medio']);headerStyle(byArea.getRow(3));byArea.columns=[{width:30},{width:13},{width:11},{width:13},{width:11},{width:13}];areaRows.forEach(a=>{const r=byArea.addRow([a.name,a.n,a.c,a.acc/100,a.p,a.avg]);r.getCell(4).numFmt='0%';r.getCell(6).numFmt='0.0';});
      const sum=wb.addWorksheet('Resumen',{views:[{showGridLines:false}]});title(sum,'Learning Hub · Informe de evolución','A1:H2');sum.mergeCells('A3:H3');sum.getCell('A3').value=`Perfil: ${prof.name} · Exportado: ${new Date().toLocaleDateString('es-ES')}`;sum.getCell('A3').font={color:{argb:muted},italic:true};sum.getCell('A5').value='INDICADOR';sum.getCell('B5').value='VALOR';headerStyle(sum.getRow(5));const end=Math.max(2,data.length+1);const metrics=[['Ejercicios realizados',{formula:`COUNTA(Detalle!A2:A${end})`,result:data.length}],['Aciertos',{formula:`COUNTIF(Detalle!F2:F${end},"Correcto")`,result:data.filter(r=>r.correct).length}],['Precisión global',{formula:'IF(B6=0,0,B7/B6)',result:data.length?data.filter(r=>r.correct).length/data.length:0}],['Puntos acumulados',{formula:`SUM(Detalle!G2:G${end})`,result:data.reduce((a,r)=>a+Number(r.points||0),0)}],['Sesiones registradas',sess.length]];metrics.forEach((m,i)=>{const row=6+i;sum.getCell(`A${row}`).value=m[0];sum.getCell(`B${row}`).value=m[1];sum.getCell(`A${row}`).font={bold:true,color:{argb:ink}};sum.getCell(`B${row}`).font={bold:true,size:14,color:{argb:accent}};});sum.getCell('B8').numFmt='0%';sum.getColumn('A').width=28;sum.getColumn('B').width=18;for(let i=3;i<=8;i++)sum.getColumn(i).width=16;
      sum.getCell('D5').value='NIVELES ACTUALES';sum.mergeCells('D5:F5');sum.getCell('D5').font={bold:true,color:{argb:white}};sum.getCell('D5').fill={type:'pattern',pattern:'solid',fgColor:{argb:headerFill}};const levels=prof.progress?.levels||{};let rr=6;Object.entries(levels).forEach(([k,v])=>{sum.getCell(`D${rr}`).value=SUBJECT_LABELS[k]||k;sum.getCell(`E${rr}`).value=`Nivel ${v}`;rr++;});
      const globalImg=wb.addImage({base64:lineChart(sess.map(s=>`S${s.num}`),sess.map(s=>s.acc),'Evolución global de la precisión'),extension:'png'});sum.addImage(globalImg,{tl:{col:0,row:12},ext:{width:780,height:278}});const areaImg=wb.addImage({base64:barChart(areaRows.map(a=>a.name),areaRows.map(a=>a.acc),'Rendimiento por áreas'),extension:'png'});sum.addImage(areaImg,{tl:{col:0,row:29},ext:{width:780,height:355}});
      [sum,evo,byArea,detail].forEach(ws=>{ws.properties.defaultRowHeight=20;ws.eachRow(row=>row.eachCell(cell=>{cell.border={bottom:{style:'hair',color:{argb:'DFE2EC'}}};}));});
      const buffer=await wb.xlsx.writeBuffer();downloadBlob(new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`LearningLab_${String(prof.name||'perfil').replace(/[^a-z0-9_-]+/gi,'_')}_evolucion.xlsx`);
    }catch(e){console.error('V16.3 Excel export',e);alert(e?.message||'No se pudo generar el informe Excel.');}finally{if(btn)btn.disabled=false;}
  }

  function worksheetGeneratorV163(){
    if(!window.docx||!window.JSZip) return false;
    function clean(v){return String(v??'').replace(/\s+/g,' ').trim();}
    function materialText(it){if(Array.isArray(it.memoryContent))return it.memoryContent.map(x=>x.person?`${x.person}: ${x.detail}`:x.detail).join(' · ');if(it.scenario)return it.scenario;if(it.title&&it.text)return `${it.title}: ${it.text}`;if(it.model)return `Modelo: ${it.model}`;if(Array.isArray(it.modelSequence))return `Modelo: ${it.modelSequence.join('  ')}`;if(Array.isArray(it.rows))return it.rows.map((r,i)=>`Fila ${i+1}: ${r.join(' ')}`).join('   |   ');if(Array.isArray(it.visualItems))return it.visualItems.join('   ');return'';}
    function promptText(it){if(it.dividend)return `${it.dividend} ÷ ${it.divisor}`;if(it.type==='order'&&Array.isArray(it.tokens))return `${it.q||'Ordena la secuencia.'}`;if(it.memoryQuestion)return it.memoryQuestion;return it.q||it.prompt||'Actividad';}
    async function makeDoc(items,version,profile){
      const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,AlignmentType,BorderStyle,Footer}=window.docx;const noBorders={top:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},bottom:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},left:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},right:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},insideHorizontal:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},insideVertical:{style:BorderStyle.NONE,size:0,color:'FFFFFF'}};const children=[];
      const header=new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:noBorders,rows:[new TableRow({children:[new TableCell({width:{size:74,type:WidthType.PERCENTAGE},shading:{fill:'ECEEFF'},margins:{top:180,bottom:180,left:220,right:160},children:[new Paragraph({children:[new TextRun({text:'FICHA DE ENTRENAMIENTO',bold:true,size:36,color:'444CAD',font:'Aptos Display'})]}),new Paragraph({children:[new TextRun({text:`Versión ${version} · ${profile.name}`,size:21,color:'24314A',font:'Aptos'})]})]}),new TableCell({width:{size:26,type:WidthType.PERCENTAGE},shading:{fill:'252B44'},margins:{top:160,bottom:160,left:100,right:100},children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'LEVEL UP',bold:true,size:26,color:'FFFFFF',font:'Aptos'})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'LEARNING LAB',bold:true,size:13,color:'D8DBEE',font:'Aptos'})]})]})]})]});children.push(header,new Paragraph({text:' '}));
      children.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:noBorders,rows:[new TableRow({children:[new TableCell({shading:{fill:'F7F4EC'},margins:{top:140,bottom:140,left:180,right:180},children:[new Paragraph({children:[new TextRun({text:'Fecha: ________________________________',size:21,color:'24314A',font:'Aptos'})]})]})]})]}));
      items.forEach((it,i)=>{children.push(new Paragraph({spacing:{before:260,after:80},children:[new TextRun({text:`ACTIVIDAD ${i+1}`,bold:true,size:16,color:'5B67D6',font:'Aptos'})]}));children.push(new Paragraph({spacing:{after:110,line:310},children:[new TextRun({text:clean(promptText(it)),bold:true,size:23,color:'24314A',font:'Aptos'})]}));const mat=clean(materialText(it));if(mat){children.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},borders:noBorders,rows:[new TableRow({children:[new TableCell({shading:{fill:'F2F3FF'},margins:{top:150,bottom:150,left:190,right:190},children:[new Paragraph({children:[new TextRun({text:'INFORMACIÓN',bold:true,size:14,color:'444CAD',font:'Aptos'})]}),new Paragraph({spacing:{before:60},children:[new TextRun({text:mat,size:20,color:'24314A',font:'Aptos'})]})]})]})]}));children.push(new Paragraph({text:''}));}
        if(it.type==='order'&&Array.isArray(it.tokens)){children.push(new Paragraph({children:[new TextRun({text:'Elementos disponibles:',bold:true,size:19,color:'6F7586',font:'Aptos'})]}));it.tokens.forEach(x=>children.push(new Paragraph({bullet:{level:0},spacing:{after:30},children:[new TextRun({text:clean(x),size:20,color:'24314A',font:'Aptos'})]})));}
        if(Array.isArray(it.opts)&&it.opts.length){children.push(new Paragraph({spacing:{before:50,after:45},children:[new TextRun({text:'Opciones:',bold:true,size:19,color:'6F7586',font:'Aptos'})]}));it.opts.forEach(x=>children.push(new Paragraph({bullet:{level:0},spacing:{after:35},indent:{left:360},children:[new TextRun({text:clean(x),size:20,color:'24314A',font:'Aptos'})]})));}
        children.push(new Paragraph({spacing:{before:90,after:20},children:[new TextRun({text:'Respuesta:',bold:true,size:18,color:'6F7586',font:'Aptos'})]}));children.push(new Paragraph({spacing:{after:40},children:[new TextRun({text:'________________________________________________________________________',size:17,color:'BCC1D0'})]}));children.push(new Paragraph({children:[new TextRun({text:'________________________________________________________________________',size:17,color:'BCC1D0'})]}));
      });const footer=new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'LEVEL UP · Learning Lab',size:16,color:'6F7586',font:'Aptos'})]})]});return Packer.toBlob(new Document({sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:620,right:720,bottom:650,left:720}}},footers:{default:footer},children}]}));
    }
    window.WorksheetGenerator={generate:async(itemsByVersion,profile)=>{if(itemsByVersion.length===1){downloadBlob(await makeDoc(itemsByVersion[0],1,profile),'LearningLab_ficha_v1.docx');return;}const zip=new JSZip();for(let i=0;i<itemsByVersion.length;i++)zip.file(`LearningLab_ficha_version_${i+1}.docx`,await makeDoc(itemsByVersion[i],i+1,profile));downloadBlob(await zip.generateAsync({type:'blob'}),`LearningLab_${itemsByVersion.length}_fichas.zip`);}};return true;
  }

  function upgrade(){
    addStyles();
    const btn=$('#exportSessionCsv');if(btn){btn.textContent='Descargar informe Excel';btn.title='Resumen, evolución global, rendimiento por áreas y detalle';btn.onclick=exportExcelV163;}
    worksheetGeneratorV163();
  }
  window.addEventListener('load',()=>{let n=0;const t=setInterval(()=>{n++;if(window.LearningAPI&&$('#appShell')){upgrade();[500,1200,2500].forEach(ms=>setTimeout(upgrade,ms));clearInterval(t);}if(n>120)clearInterval(t);},100);});
})();
